In [1]:
import pandas as pd
import numpy as np

estoque = pd.read_csv("retail_inventory_ml_apl.csv")
display(estoque.head(5))

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
0,2025-08-07,2025-10-18,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,STR-1010,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75
1,2026-02-15,2026-02-15,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,STR-1082,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73
2,2026-01-08,2026-02-15,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,STR-1105,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44
3,2025-12-23,2026-02-15,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,STR-1157,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50
4,2026-02-10,9999-12-31,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,STR-1253,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54

In [2]:
#informacoes e possiveis tratamentos
print(estoque.duplicated().sum())


display(estoque.info())
display(estoque.describe())

0
<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  str
 1   End Date                  284755 non-null  str
 2   Stock Status              284755 non-null  str
 3   Supplier                  284755 non-null  str
 4   Product No                284755 non-null  str
 5   Product Description       284755 non-null  str
 6   Product Division          284755 non-null  str
 7   Product Category          284755 non-null  str
 8   Product Subcategory       284755 non-null  str
 9   Product Segment           284755 non-null  str
 10  Store                     284755 non-null  str
 11  Store Type                284755 non-null  str
 12  Sales Channel             284755 non-null  str
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: float64(4), int64(1), str(13)
memory usage: 39.1 MB

None

,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
count,284755.000000,284755.000000,284755.000000,284755.000000,284755.000000
mean,2.294629,224.392566,111.046256,95.313171,47.419488
std,2.007395,214.479811,105.785092,46.655771,23.776569
min,-9.000000,-828.000000,-418.950000,0.000000,-16.940000
25%,1.000000,95.000000,46.430000,75.000000,37.950000
50%,2.000000,160.000000,80.960000,100.000000,50.050000
75%,3.000000,300.000000,149.170000,120.000000,60.720000
max,56.000000,5600.000000,2641.450000,250.000000,336.380000

In [3]:
#tratando tipo data
estoque['Start Date'] = pd.to_datetime(estoque['Start Date'])
estoque['End Date'] = pd.to_datetime(estoque['End Date'])

estoque.info()

<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  datetime64[us]
 1   End Date                  284755 non-null  datetime64[us]
 2   Stock Status              284755 non-null  str
 3   Supplier                  284755 non-null  str
 4   Product No                284755 non-null  str
 5   Product Description       284755 non-null  str
 6   Product Division          284755 non-null  str
 7   Product Category          284755 non-null  str
 8   Product Subcategory       284755 non-null  str
 9   Product Segment           284755 non-null  str
 10  Store                     284755 non-null  str
 11  Store Type                284755 non-null  str
 12  Sales Channel             284755 non-null  str
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: datetime64[us](2), float64(4), int64(1), str(11)
memory usage: 39.1 MB

In [ ]:
#retirando dados

#quantos produtos existem
pdts = estoque['Product No'].nunique()
print(pdts)

#quantos fornecedores
frnc = estoque['Supplier'].nunique()
print(frnc)

#quantas lojas
ljs = estoque['Store'].nunique()
print(ljs)

#quantas categorias
cat = estoque['Product Category'].nunique()
print(cat)

#valor total estoque
vlr_estoq=estoque['Cost of Stocks'].sum()
print(f'{vlr_estoq:,.2f}')

#valor potencial de venda
vlr=estoque['Stocks Selling Amount'].sum()
print(f'{vlr:,.2f}')

#Criando coluna lucro
estoque['Profit'] = estoque['Stocks Selling Amount'] - estoque['Cost of Stocks']

2326
30
40
27
31,620,976.61
63,896,905.11
32,275,928.50

In [ ]:
#Analises
#categoria mais lucrativa
cat_lucro = estoque[['Product Category', 'Profit']].groupby('Product Category').sum()
cat_lucro = cat_lucro.sort_values(by= 'Profit', ascending= False)
#display(cat_lucro)

#segmentos mais lucartivos
seg_lucro = estoque[['Product Segment', 'Profit']].groupby('Product Segment').sum()
seg_lucro = seg_lucro.sort_values(by='Profit', ascending=False)
#display(seg_lucro)

#lucro subcategoria
subc_lucro = estoque[['Product Subcategory', 'Profit']].groupby('Product Subcategory').sum()
subc_lucro = subc_lucro.sort_values(by='Profit', ascending= False)
#display(subc_lucro)

In [28]:
#fonecedores
#fornecedor que gera mais lucro
forn_lucro = estoque[['Supplier', 'Profit']].groupby('Supplier').sum()
forn_lucro = forn_lucro.sort_values(by= 'Supplier', ascending=False)
#display(forn_lucro)

#maior estoque
estoq_forn = estoque[['Supplier', 'Stock Status']].groupby('Supplier').count()
estoq_forn = estoq_forn.sort_values(by='Stock Status', ascending=False)
#display(estoq_forn)

#qual fornecedor possui mais produtos
prod_forn = estoque[['Supplier', 'Product No']].groupby('Supplier').count()
prod_forn = prod_forn.sort_values(by= 'Product No', ascending=False)
#display(prod_forn)

#lojas
#loja com maior estoque
estoq_loja = estoque[['Store', 'Qty on hand']].groupby('Store').sum()
estoq_loja = estoq_loja.sort_values(by='Qty on hand', ascending=False)
#display(estoq_loja)

#loja com maior valor em vendas
loja_venda_estoque = estoque[['Store', 'Stocks Selling Amount']].groupby('Store', as_index= False).sum()
loja_venda_estoque = loja_venda_estoque.sort_values(by='Stocks Selling Amount', ascending=False)
#display(loja_venda_estoque)

#loja mais lucrativa
loja_lucro = estoque[['Store', 'Profit']].groupby('Store').sum()
loja_lucro = loja_lucro.sort_values(by= 'Profit', ascending=False)
display(loja_lucro)

              Profit
Store
STR-1006  1409886.63
STR-1229  1112001.86
STR-1010  1051525.79
STR-1044  1045841.32
STR-1222  1018292.84
STR-1094   999677.17
STR-1198   985655.93
STR-1109   984911.24
STR-1148   957519.38
STR-1080   940309.28
STR-1194   939623.04
STR-1145   931717.11
STR-1075   922113.92
STR-1235   911336.42
STR-1350   862776.50
STR-1253   856300.36
STR-1203   829245.92
STR-1305   799160.11
STR-1038   798138.79
STR-1114   797987.31
STR-1085   780413.98
STR-1026   779659.08
STR-1107   763821.41
STR-1163   742207.74
STR-1338   740401.91
STR-1157   733929.15
STR-1348   726328.46
STR-1219   722464.66
STR-1074   702011.31
STR-1237   663176.21
STR-1255   647816.26
STR-1308   634954.66
STR-1082   625364.16
STR-1149   588427.97
STR-1335   576533.54
STR-1353   574912.78
STR-1369   567667.74
STR-1234   555156.13
STR-1344   519805.99
STR-1105   476854.44