In [2]:
#Analise de dados chocolate
import pandas as pd
import numpy as np

df_sales = pd.read_csv("Chocolate_Sales.csv")
display(df_sales)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69
...,...,...,...,...,...,...,...,...,...,...,...
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91

In [3]:
print(df_sales.duplicated().sum())

print(df_sales.isnull().sum())

display(df_sales.info())

qtd_prod=df_sales['Product'].nunique()
print(qtd_prod)

0
Order_ID             0
Product              0
Country              0
Channel              0
Salesperson          0
Order_Date         437
Discount_Pct       489
Price_per_Box      457
Marketing_Spend    461
Boxes_Shipped        0
Amount               0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         200000 non-null  str
 1   Product          200000 non-null  str
 2   Country          200000 non-null  str
 3   Channel          200000 non-null  str
 4   Salesperson      200000 non-null  str
 5   Order_Date       199563 non-null  str
 6   Discount_Pct     199511 non-null  float64
 7   Price_per_Box    199543 non-null  float64
 8   Marketing_Spend  199539 non-null  float64
 9   Boxes_Shipped    200000 non-null  int64
 10  Amount           200000 non-null  str
dtypes: float64(3), int64(1), str(7)
memory usage: 16.8 MB

None

12

In [4]:
#price_null=df_sales[df_sales['Price_per_Box'].isna()]
#display(price_null)

df_sales['Amount'] = ( df_sales['Amount'] .str.replace('$', '', regex=False) .str.replace(',', '', regex=False) .astype(float) )
df_sales['Amount'] = df_sales['Amount'].astype(float)

df_sales= df_sales.dropna()

display(df_sales.info())

<class 'pandas.DataFrame'>
Index: 198397 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         198397 non-null  str
 1   Product          198397 non-null  str
 2   Country          198397 non-null  str
 3   Channel          198397 non-null  str
 4   Salesperson      198397 non-null  str
 5   Order_Date       198397 non-null  str
 6   Discount_Pct     198397 non-null  float64
 7   Price_per_Box    198397 non-null  float64
 8   Marketing_Spend  198397 non-null  float64
 9   Boxes_Shipped    198397 non-null  int64
 10  Amount           198397 non-null  float64
dtypes: float64(4), int64(1), str(6)
memory usage: 18.2 MB

None

In [5]:
#Analise descritiva vendas internacionais de chocolate
#fato pais
maior_receita_pais = df_sales[["Country", "Amount"]].groupby('Country').sum()
maior_receita_pais = maior_receita_pais.sort_values(by="Country", ascending=True)
maior_receita_pais['Amount'] =maior_receita_pais['Amount'].map("R${:,.2f}".format)

display(maior_receita_pais)

                    Amount
Country
Australia  R$42,091,134.12
Brazil     R$36,347,661.46
Germany    R$11,256,585.62
India       R$6,441,175.05
Japan       R$5,610,066.73

In [6]:
#produto com mais lucro em cada pais
produto_pais=df_sales[["Country", "Product", "Amount"]].groupby(['Country', 'Product']).sum()
produto_pais = produto_pais.sort_values(by=['Country','Amount'], ascending=False)
produto_pais['Amount'] =produto_pais['Amount'].map("R${:,.2f}".format)
#display(produto_pais)

#produto mais vendido (caixas enviadas) por pais
caixas_env= df_sales[["Country", "Product", "Boxes_Shipped","Amount"]].groupby(['Country', 'Product']).sum()
caixas_env= caixas_env.sort_values(by=['Country','Boxes_Shipped'], ascending=False)
caixas_env['Amount'] =caixas_env['Amount'].map("R${:,.2f}".format)
display(caixas_env)

                                Boxes_Shipped           Amount
Country   Product
Japan     70% Dark Bar                 376210   R$1,372,969.68
          Truffle Gift Box             291629   R$1,079,720.70
          Mixed Assortment Box         283845   R$1,053,173.00
          Almond Crunch Bar             99475     R$340,871.44
          Milk Classic Bar              98522     R$362,657.13
          Pralines Gift Box             84459     R$308,608.08
          Choco Coins Bag               78952     R$277,740.03
          Mint Dark Bar                 51464     R$191,693.38
          White Choco Bar               48720     R$185,387.05
          85% Dark Bar                  44674     R$168,414.75
          Salted Caramel Bar            39524     R$150,830.32
          Hazelnut Milk Bar             30858     R$118,001.17
India     70% Dark Bar                 442414   R$1,624,414.88
          Mixed Assortment Box         335499   R$1,222,686.46
          Truffle Gift Box             327872   R$1,234,330.37
          Milk Classic Bar             107316     R$397,468.12
          Almond Crunch Bar            101247     R$380,058.65
          Pralines Gift Box             97313     R$355,890.90
          Choco Coins Bag               82257     R$304,767.31
          Mint Dark Bar                 63273     R$230,667.05
          White Choco Bar               53614     R$190,801.50
          85% Dark Bar                  50741     R$187,707.43
          Salted Caramel Bar            47981     R$175,260.11
          Hazelnut Milk Bar             37650     R$137,122.27
Germany   70% Dark Bar                 780485   R$2,867,728.95
          Mixed Assortment Box         610099   R$2,213,096.33
          Truffle Gift Box             575340   R$2,114,041.16
          Milk Classic Bar             187123     R$699,023.39
          Almond Crunch Bar            171046     R$644,595.38
          Pralines Gift Box            167207     R$595,715.23
          Choco Coins Bag              151211     R$545,490.39
          Mint Dark Bar                100103     R$367,277.65
          White Choco Bar               94044     R$352,847.87
          85% Dark Bar                  84558     R$309,556.78
          Salted Caramel Bar            84535     R$310,592.94
          Hazelnut Milk Bar             67608     R$236,619.55
Brazil    70% Dark Bar                2564932   R$9,360,716.95
          Truffle Gift Box            1882267   R$6,860,488.62
          Mixed Assortment Box        1882059   R$6,931,162.09
          Milk Classic Bar             589790   R$2,176,987.26
          Pralines Gift Box            569358   R$2,082,358.49
          Almond Crunch Bar            553336   R$2,010,095.10
          Choco Coins Bag              447182   R$1,666,664.72
          Mint Dark Bar                336724   R$1,244,853.03
          White Choco Bar              322087   R$1,169,008.26
          85% Dark Bar                 294029   R$1,093,554.15
          Salted Caramel Bar           258810     R$966,651.11
          Hazelnut Milk Bar            220949     R$785,121.68
Australia 70% Dark Bar                2954817  R$10,933,848.22
          Mixed Assortment Box        2188324   R$7,984,914.28
          Truffle Gift Box            2145577   R$7,949,208.70
          Milk Classic Bar             698432   R$2,559,971.19
          Pralines Gift Box            646551   R$2,366,335.29
          Almond Crunch Bar            642536   R$2,356,730.45
          Choco Coins Bag              518277   R$1,944,751.94
          Mint Dark Bar                397564   R$1,454,322.62
          White Choco Bar              354213   R$1,298,837.20
          85% Dark Bar                 322873   R$1,184,841.39
          Salted Caramel Bar           315167   R$1,179,035.25
          Hazelnut Milk Bar            236553     R$878,337.59

In [7]:
#Fato Marketing
#Qual pais gastou mais com marketing

marketing = df_sales[['Marketing_Spend', 'Country']].groupby('Country').sum()
marketing = marketing.sort_values(by='Country', ascending=True)
marketing['Marketing_Spend'] =marketing['Marketing_Spend'].map("R${:,.2f}".format)
display(marketing)

#lucro total paises
lucro_pais = df_sales[['Amount', 'Country']].groupby('Country').sum()
lucro_pais = lucro_pais.sort_values(by='Country', ascending=True)
lucro_pais['Amount'] =lucro_pais['Amount'].map("R${:,.2f}".format)
display(lucro_pais)

          Marketing_Spend
Country
Australia  R$8,754,072.62
Brazil     R$5,031,163.68
Germany    R$2,388,069.22
India      R$1,660,835.52
Japan      R$1,102,325.41

                    Amount
Country
Australia  R$42,091,134.12
Brazil     R$36,347,661.46
Germany    R$11,256,585.62
India       R$6,441,175.05
Japan       R$5,610,066.73

In [8]:
#fato desconto
#faixas de descontos
#med_desc = df_sales['Discount_Pct'].mean()
#print(med_desc)


faixas = [0, 8.3, 13.1, 17.5, 38.3]

cat = ["Baixo", "Medio", "Alto", 'Muito alto']

df_sales["Desconto"] = pd.cut(df_sales["Discount_Pct"], bins= faixas, labels=cat)

display(df_sales.head())

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Desconto
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,Baixo
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,Medio
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.70,Baixo
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,Alto
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,Baixo

In [9]:
#A faixa de desconto influencia nos ganhos
desconto_ganhos = df_sales[['Desconto', 'Amount']].groupby('Desconto').sum()
desconto_ganhos = desconto_ganhos.sort_values(by='Amount', ascending= False)
desconto_ganhos['Amount'] =desconto_ganhos['Amount'].map("R${:,.2f}".format)
display(desconto_ganhos)

                     Amount
Desconto
Medio       R$27,408,058.15
Muito alto  R$26,635,541.05
Baixo       R$24,488,942.43
Alto        R$23,213,769.60

In [10]:
desconto_canal = df_sales[['Desconto', 'Channel', 'Amount']].groupby(['Desconto', 'Channel']).sum()
desconto_canal = desconto_canal.sort_values(by='Amount', ascending= False)
desconto_canal['Amount'] =desconto_canal['Amount'].map("R${:,.2f}".format)
display(desconto_canal)

                               Amount
Desconto   Channel
Medio      Retail     R$14,369,832.66
Muito alto Retail     R$13,989,031.61
Baixo      Retail     R$12,835,747.37
Alto       Retail     R$12,159,056.85
Medio      Wholesale   R$9,939,065.54
Muito alto Wholesale   R$9,662,685.62
Baixo      Wholesale   R$9,009,234.02
Alto       Wholesale   R$8,572,041.89
Medio      Online      R$3,099,159.95
Muito alto Online      R$2,983,823.82
Baixo      Online      R$2,643,961.04
Alto       Online      R$2,482,670.86

In [11]:
#df_sales['Order_Date']
display(df_sales['Order_Date'].max())
display(df_sales['Order_Date'].min())

'31/12/2023'

'01 Jan 2022'